package server;

import java.io.*;
import java.net.Socket;

/**
 * A class to handle the file requested in the URL
 * Created by Hatem on 2/23/2016.
 */
public class FileHandler {

    private char fileType;
    private int httpCode;
    private HTTPResponse httpResponse;
    public final int OK = 200;
    public final int NOT_FOUND = 404;
    public final int FORBIDDEN = 403;
    public final int INTERNAL_ERROR = 500;


    public char checkFileType(String filePath) {
        if (filePath.endsWith(".html") || filePath.endsWith(".htm"))
            fileType = 'h';
        else if (filePath.endsWith(".png"))
            fileType = 'p';
        else if (filePath.endsWith(".ico"))         //for favicon.ico files that are automatically generated by some browsers e.g. Google Chrome
            fileType = 'i';
        else {
            httpCode = NOT_FOUND;                     //code 403 Forbidden
        }
        return fileType;
    }

    public File checkValidity(String filePath){
        httpResponse = new HTTPResponse();
        File file = new File(filePath);

        if (filePath.equals("!SERVER#500#ERROR=flag+")|| filePath.isEmpty()){
            httpCode = INTERNAL_ERROR;
            file = new File ("src\\500InternalServerError.html");
        }

        if(!filePath.startsWith("files"))
            file = new File("src\\403Forbidden.html");
        else if(!file.exists() && httpCode != FORBIDDEN) {
            httpCode = NOT_FOUND;
            file = new File("src\\404FileNotFound.html");
        } else{
            httpCode = OK; //}
        }

        return file;
    }

    public void readFile(Socket socket, File file){
        try {
            DataOutputStream output = new DataOutputStream(socket.getOutputStream());
            FileInputStream reader = new FileInputStream(file);       // create a reader for the required file

            byte[] buf = new byte[1024];
            int count;                                      //Counter to know the end of the file

            httpResponse.formHTTPResponse(httpCode, file, fileType);
            System.out.println(httpResponse.getResponse());              //Write the http response header

            while ((count = reader.read(buf)) >= 0)                     //Write the http response body
                output.write(buf, 0, count);

            output.close();
            reader.close();
        } catch (IOException e) {
            System.err.print("500 - Internal Server Error 500\n");
            readFile(socket,this.checkValidity("!SERVER#500#ERROR=flag+"));
            e.printStackTrace();
        }
    }
}
